version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
      - api

  api:
  build:
    context: ./back
    dockerfile: Dockerfile
  environment:
    DHOST: db
    DUSER: user
    NAME: mydatabase
    PASSWORD: password
    DPORT: 3306
  ports:
    - "3000:3000"
  depends_on:
    - db
  command: ["wait-for-it.sh", "db:3306", "--", "npm", "start"]


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: